#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

int play_user(void);

int roll_a_dice(void);

int play_pc();

int scoresheet(int,int);

//"user" and "player" might have been used interchangeably in the comments through the code//

int main() {
    int rounds , initialization , totalscorepc , totalscoreuser , roundholder , computerr , userr;
    userr = 0;
    computerr = 0;
    //initializing userr and computerr variables//

    printf("Welcome to Generala game\n\n");
    rounds = -1;
    do {
        printf("How many times would you like to play?\n");
        scanf("%d", &rounds);
        if (rounds <= 0) {
            printf("\n<Please Enter A Valid Value>\n\n");
        }
    }
    while (rounds <=0);
    // asks user how many rounds they would like to play until they input a valid value //



    for (initialization=1 ; initialization<=rounds ; initialization++) {
        totalscorepc = 0;
        totalscoreuser = 0;
        roundholder = 1;
        // a nested loop so game count and round count can coexist , it will first run through amount of games that will be played and start countring rounds in that game//
        while (computerr == userr) {
            userr = roll_a_dice();
            computerr = roll_a_dice();
            printf("\nYou Rolled : %d , I Rolled : %d\n" , userr , computerr);
            if (computerr == userr) {
                printf("\nLooks Like We Got The Same Value I Am Rolling Again!\n");
            }
        }

        while (computerr != userr) {
            // checks who won the initial dice roll to see who will play first and act accordingly //
            if (userr > computerr) {
                while (totalscorepc < 50 && totalscoreuser < 50) {
                    printf("\nRound %d -- Your Turn " , roundholder);
                    roundholder++;
                    // counts the round by adding 1 to the roundholder variable every round //
                    totalscoreuser = totalscoreuser + play_user();
                    totalscorepc = totalscorepc + play_pc();
                    // calculates the scores //
                    scoresheet(totalscorepc , totalscoreuser);
                    // uses the scoresheet function to display the scores //
                }

            }
            else if (computerr > userr) {
                while (totalscorepc < 50 && totalscoreuser < 50) {
                    printf("\nRound %d -- Your Turn " , roundholder);
                    roundholder++;
                    // counts the round by adding 1 to the roundholder variable every round //
                    totalscorepc = totalscorepc + play_pc();
                    totalscoreuser = totalscoreuser + play_user();
                    // calculates the scores //
                    scoresheet(totalscorepc , totalscoreuser);
                    // uses the scoresheet function to display the scores //
                }
        }


        }


    }


    return 0 ;


}


int roll_a_dice(void) {
    //a simple dice function that checks for remainings from any value generated by computer which then will be a number between 0 and 5 which adding 1 would give us a number between 1 and 6//
    return (rand() % 6) + 1;
}


int calculate_score(int a1 , int a2 , int a3 , int a4 , int a5) {
    // this function calculates the score that comes from dice which is used in playerturn and computerturn functions//
    // checks every possible outcome and uses a substitue variable to check if score is higher than we could have gotten any other way//
    int scoreholder , scorecount;

    scoreholder = 1;
    scorecount = 0;

    if (a1 == 1) {
        scorecount = scorecount + 1;
    }
    if (a2 == 1) {
        scorecount = scorecount + 1;;
    }
    if (a3 == 1) {
        scorecount = scorecount + 1;;
    }
    if (a4 == 1) {
        scorecount = scorecount + 1;;
    }
    if (a5 == 1) {
        scorecount = scorecount + 1;;
    }

    if (scorecount > scoreholder) {
        scoreholder = scorecount;
    }
    scorecount = 0;

    if (a1 == 2) {
        scorecount = scorecount + 2;
    }
    if (a2 == 2) {
        scorecount = scorecount + 2;
    }
    if (a3 == 2) {
        scorecount = scorecount + 2;
    }
    if (a4 == 2) {
        scorecount = scorecount + 2;
    }
    if (a5 == 2) {
        scorecount = scorecount + 2;
    }

    if (scorecount > scoreholder) {
        scoreholder = scorecount;
    }
    scorecount = 0;

    if (a1 == 3) {
        scorecount = scorecount + 3;
    }
    if (a2 == 3) {
        scorecount = scorecount + 3;
    }
    if (a3 == 3) {
        scorecount = scorecount + 3;
    }
    if (a4 == 3) {
        scorecount = scorecount + 3;
    }
    if (a5 == 3) {
        scorecount = scorecount + 3;
    }

    if (scorecount > scoreholder) {
        scoreholder = scorecount;
    }
    scorecount = 0;

    if (a1 == 4) {
        scorecount = scorecount + 4;
    }
    if (a2 == 4) {
        scorecount = scorecount + 4;
    }
    if (a3 == 4) {
        scorecount = scorecount + 4;
    }
    if (a4 == 4) {
        scorecount = scorecount + 4;
    }
    if (a5 == 4) {
        scorecount = scorecount + 4;
    }

    if (scorecount > scoreholder) {
        scoreholder = scorecount;
    }
    scorecount = 0;

    if (a1 == 5) {
        scorecount = scorecount + 5;
    }
    if (a2 == 5) {
        scorecount = scorecount + 5;
    }
    if (a3 == 5) {
        scorecount = scorecount + 5;
    }
    if (a4 == 5) {
        scorecount = scorecount + 5;
    }
    if (a5 == 5) {
        scorecount = scorecount + 5;
    }

    if (scorecount > scoreholder) {
        scoreholder = scorecount;
    }
    scorecount = 0;

    if (a1 == 6) {
        scorecount = scorecount + 6;
    }
    if (a2 == 6) {
        scorecount = scorecount + 6;
    }
    if (a3 == 6) {
        scorecount = scorecount + 6;
    }
    if (a4 == 6) {
        scorecount = scorecount + 6;
    }
    if (a5 == 6) {
        scorecount = scorecount + 6;
    }

    if (scorecount > scoreholder) {
        scoreholder = scorecount;
    }
    scorecount = 0;





    if (a1 == a2 && a1 == a3 && a1 == a4 && a1 == a5) {
        if (scoreholder<50) {
            scoreholder = 50;
        }
    }

    if ((a1 == a2 && a1 == a3 && a1 == a4) || (a1 == a2 && a1 == a3 && a1 == a5) || (a1 == a2 && a1 == a4 && a1 == a5) || (a1 == a3 && a1 == a4 && a1 == a5) || (a2 == a3 && a2 == a4 && a2 == a5)) {
        if (scoreholder < 40) {
            scoreholder = 40;
        }
    }

    if ((a1 == a2 && a1 == a3 && a4 == a5) || (a1 == a2 && a1 == a4 && a3 == a5) || (a1 == a2 && a1 == a5 && a3 == a4) || (a1 == a3 && a1 == a4 && a2 == a5) || (a1 == a3 && a1 == a5 && a2 == a4) || (a1 == a4 && a1 == a5 && a2 == a3) || (a2 == a3 && a2 == a4 && a1 == a5) || (a2 == a3 && a2 == a5 && a1 == a4) || (a2 == a4 && a2 == a5 && a1 == a3) || (a3 == a4 && a3 == a5 && a1 == a2) || (a3 == a4 && a3 == a2 && a1 == a5) || (a4 == a5 && a4 == a2 && a1 == a3)) {
        if (scoreholder < 30) {
            scoreholder = 30;
        }
    }
    if (a1+1 == a2 && a2+1 == a3 && a3+1 == a4 && a4+1 == a5) {
        if (scoreholder < 20) {
            scoreholder = 20;
        }
    }






    return scoreholder;
    // returns the highest possible outcome //
}






int play_user(void) {
        int dice1 , dice2 , dice3 , dice4 , dice5 , skip1 , skip2 , scoreassumer;
        char wantroll;
        bool is_rollagain; //although I used boolean here I could also use integer changing true with 1 and false with 0//
        is_rollagain = false;
    //initializing skip 1 and skip2//
        skip1 = 7;
        skip2 = 7;
        dice1 = roll_a_dice();
        dice2 = roll_a_dice();
        dice3 = roll_a_dice();
        dice4 = roll_a_dice();
        dice5 = roll_a_dice();
        scoreassumer = calculate_score(dice1 , dice2 , dice3 , dice4 , dice5); //a placeholder variable so we can change it if the user wants to reroll/</
        printf ("You got -> [Dice 1] : %d , [Dice 2] : %d , [Dice 3] : %d , [Dice 4] : %d , [Dice 5] : %d" , dice1 , dice2 , dice3 , dice4 , dice5);
        printf ("\n Shall I roll for you? (Y/N) : ");
        scanf (" %c" , &wantroll);
    // uses boolean variable to check if user wants to reroll//
        if (wantroll == 'Y') {
            is_rollagain = true;
        }
        else if (wantroll != 'N') {
            printf("Please Enter A Valid Value \n \n");
            // it will ask the user to put a valid value only once and keep asking if it should roll until a valid value is entered//
            while (wantroll != 'Y' && wantroll != 'N') {
                printf("\n Shall I Roll For You? (Y/N) : ");
                scanf(" %c" , &wantroll);
            }
        }
        if (wantroll == 'Y') {
            is_rollagain = true;
    }
        // if user input "Y" it will ask for which dices to keep and will roll again //
        if (is_rollagain == true) {
            printf("Which Ones Do You Want To Keep? : ");
            scanf("%d %d" , &skip1 , &skip2);
            if (skip1 != 1 && skip2 != 1) {
                dice1 = roll_a_dice();
            }
            if (skip1 != 2 && skip2 != 2) {
                dice2 = roll_a_dice();
            }
            if (skip1 != 3 && skip2 != 3) {
                dice3 = roll_a_dice();
            }
            if (skip1 != 4 && skip2 != 4) {
                dice4 = roll_a_dice();
            }
            if (skip1 != 5 && skip2 != 5) {
                dice5 = roll_a_dice();
            }
            printf ("\nYou rolled again and got -> [Dice 1] : %d , [Dice 2] : %d , [Dice 3] : %d , [Dice 4] : %d , [Dice 5] : %d" , dice1 , dice2 , dice3 , dice4 , dice5);
            scoreassumer = calculate_score(dice1 , dice2 , dice3 , dice4 , dice5);
            is_rollagain = false;

        }
        //since value might have changed from reroll I used scoreassumer the whole time instead of simple "return"s which then is returned at the end of the function to get the user score//
        return scoreassumer;
    }

int play_pc(void) {
    int dice1 , dice2 , dice3 , dice4 , dice5;

    dice1 = roll_a_dice();
    dice2 = roll_a_dice();
    dice3 = roll_a_dice();
    dice4 = roll_a_dice();
    dice5 = roll_a_dice();
    // rolls dice for the first time//

    printf ("\nI got -> [Dice 1] : %d , [Dice 2] : %d , [Dice 3] : %d , [Dice 4] : %d , [Dice 5] : %d" , dice1 , dice2 , dice3 , dice4 , dice5);
    // prints the initial value from the dice  //
    // on the lines below it implements the computer strategy by checking if the computer is close to a generala //
    if (dice1 == dice2 && dice1 == dice3 && dice1 == dice4 && dice1 != dice5) {
        dice5 = roll_a_dice();
        printf ("I rolled again and got -> [Dice 1] : %d , [Dice 2] : %d , [Dice 3] : %d , [Dice 4] : %d , [Dice 5] : %d" , dice1 , dice2 , dice3 , dice4 , dice5);
    }
    else if (dice2 == dice3 && dice2 == dice4 && dice2 == dice5 && dice2 != dice1) {
        dice1 = roll_a_dice();
        printf ("I rolled again and got -> [Dice 1] : %d , [Dice 2] : %d , [Dice 3] : %d , [Dice 4] : %d , [Dice 5] : %d" , dice1 , dice2 , dice3 , dice4 , dice5);
    }
    else if (dice3 == dice4 && dice3==dice5 && dice5==dice1) {
        dice2 = roll_a_dice();
        printf ("I rolled again and got -> [Dice 1] : %d , [Dice 2] : %d , [Dice 3] : %d , [Dice 4] : %d , [Dice 5] : %d" , dice1 , dice2 , dice3 , dice4 , dice5);
    }
    else if (dice4 == dice5 && dice4 == dice1 && dice4 == dice2 && dice4 != dice3) {
        dice3 = roll_a_dice();
        printf ("I rolled again and got -> [Dice 1] : %d , [Dice 2] : %d , [Dice 3] : %d , [Dice 4] : %d , [Dice 5] : %d" , dice1 , dice2 , dice3 , dice4 , dice5);
    }
    else if (dice5 == dice1 && dice5 == dice5 == dice2 && dice5 == dice3 && dice5 != dice4) {
        dice4 = roll_a_dice();
        printf ("I rolled again and got -> [Dice 1] : %d , [Dice 2] : %d , [Dice 3] : %d , [Dice 4] : %d , [Dice 5] : %d" , dice1 , dice2 , dice3 , dice4 , dice5);
    }


    return calculate_score(dice1 , dice2 , dice3 , dice4 , dice5);
    //returns the final dice values//


}

int scoresheet(totalscorepc , totalscoreuser) {
    printf(" \nComputer \t\t\t\t\t Player\n");
    printf("%d \t\t\t\t\t\t %d" , totalscorepc , totalscoreuser);
    // displays the current scoreboard on the current game and round//

    // on the lines below it checks if anyone won yet and prints a message based on if anyone won//
    if (totalscorepc >= 50) {
        printf("\nComputer Won!\n");
    }
    else if (totalscoreuser >= 50) {
        printf("\nUser Won!\n");
    }
    return 0;
}






